---
title: "Projects"
format: html
editor: visual
---
- [Making a Research Website with Github Pages and Quarto](https://github.com/alburycatalina/Personal-Research-Website/blob/main/README.md)\
[{code}](https://github.com/alburycatalina/Personal-Research-Website)\
    A tutorial for making a personal research website with Github and Quarto. 
-   [BETA Reporting](https://github.com/alburycatalina/BETA-Reporting)\
    [{code}](https://github.com/alburycatalina/BETA-Reporting)\
    Code for generating insights about participation in BETA (Bahamas Engineering and Technological Advancement) using spatial data analysis packages [geodata](https://cran.r-project.org/web/packages/geodata/index.html), [sf](https://r-spatial.github.io/sf/), [terra](https://cran.r-project.org/web/packages/terra/index.html), and [tmap](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html).

-   [Data Practices for Open Science](https://alburycatalina.github.io/data-practices/data-practices-for-open-science.html#/title-slide)\
    [{code}](https://github.com/alburycatalina/data-practices)\
    Materials for a talk to the [Earth to Ocean research group](https://earthtooceansfu.ca/) at Simon Fraser University. This presentation serves as an introduction to practical applications of the "FAIR" method for scientific data management and stewardship.

-   [Employment Equity: An Analysis of Distribution of Salary Ranges of Public Service of Canada Employees](https://employment-equity.github.io/)\
    [{code}](https://github.com/Employment-Equity/employment-equity.github.io)\
    Code used to webscrape and visualize employee salary data from the Government of Canada's Treasury Board. Here we demonstrate systemic disadvantage in career progression amongst Black public servants which must be resolved with a strategic plan to identify structural and systemic barriers and improve retention and success to levels achieved by their non-racialized peers.

-   [Differential Protein Expression with Bayes Quasi-Likelihood in edgeR](https://github.com/alburycatalina/Fracy_TMT_DifferentialExpression)\
    [{code}](https://github.com/alburycatalina/Fracy_TMT_DifferentialExpression)\
    Code used to determine which proteins are differentially expressed in the treatment cultures when compared to control using bioconductor's [edgeR](https://bioconductor.org/packages/release/bioc/html/edgeR.html).

-   [Planet aRt](https://github.com/alburycatalina/planet-aRt)\
    [{code}](https://github.com/alburycatalina/planet-aRt/blob/main/planet-aRt.R)\
    My attempt at making some pretty things with the generative art package, aRtsy.

-   [Thesis Word Cloud](https://github.com/alburycatalina/ThesisWordCloud)\
    [{code}](https://github.com/alburycatalina/ThesisWordCloud/blob/main/thesis_wordcloud.R)\
    A quick little repo containing a script I used to create a word cloud from my thesis. Here I make a visually appealing representation of the frequency of words used to tell the story of what I've been working on for the past two and a half years.

-   [Coding Nature](https://github.com/alburycatalina/Coding-Nature)\
    A repository for a workshop for Black high school students in Nova Scotia (ages 13+). This workshop aims to inspire passion for nature and science, while giving an introduction to coding logic and data. The included exercises demonstrate how we can use programming as a tool to improve our understanding of the world around us.

-   [Intro to Coding for Sr. High](https://github.com/alburycatalina/FHA_intro_to_coding)\
    Code for a 2-day introductory coding tutorial for Bahamian high school students at Forest Heights Academy.

## 
